severity:
  critical:
    - aws_iam_role
    - aws_iam_policy
    - aws_iam_user
    - aws_security_group
    - aws_vpc
    - aws_subnet
    - aws_route_table
    - aws_nacl
    - aws_kms_key
  high:
    - aws_db_instance
    - aws_rds_cluster
    - aws_s3_bucket
    - aws_cloudfront_distribution
    - aws_lb
    - aws_lb_listener
    - aws_eks_cluster
  medium:
    - aws_instance
    - aws_lambda_function
    - aws_dynamodb_table
    - aws_sqs_queue
    - aws_sns_topic
    - aws_autoscaling_group
  low:
    - aws_s3_bucket_object
    - aws_cloudwatch_log_group
    - aws_tag
    - aws_route53_record
